# Generated by Django 5.1.1 on 2024-10-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upper_body_clothes', models.IntegerField(default=0)),
                ('lower_body_clothes', models.IntegerField(default=0)),
                ('underwear', models.IntegerField(default=0)),
                ('other_stuff', models.IntegerField(default=0)),
                ('pImage', models.URLField()),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
