# Generated by Django 5.1.1 on 2024-11-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userprofile_user_type_business_customer_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('looking_for_driver', 'Looking for Driver'), ('driver_on_the_way_to_pickup', 'Driver on the way to pickup'), ('driver_on_the_way_to_laundry', 'Driver on the way to laundry'), ('laundry_received', 'Laundry received'), ('laundry_cleaning', 'Laundry cleaning'), ('driver_on_the_way_to_customer', 'Driver on the way to customer'), ('delivered', 'Delivered'), ('finished', 'Finished')], default='looking_for_driver', max_length=50),
        ),
    ]
