# Generated by Django 5.1.3 on 2024-11-28 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='user_profile',
        ),
        migrations.CreateModel(
            name='BusinessOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=50)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_owner_profile', to='users.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='business',
            name='business_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='business_owner', to='users.businessowner'),
            preserve_default=False,
        ),
    ]
