# Generated by Django 5.1.3 on 2024-11-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_service_heavy_tendency_maximum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='heavy_tendency_maximum',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='service',
            name='heavy_tendency_minimum',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='service',
            name='heavy_tendency_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='service',
            name='light_tendency_maximum',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='service',
            name='light_tendency_minimum',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='service',
            name='light_tendency_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='service',
            name='medium_tendency_maximum',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='service',
            name='medium_tendency_minimum',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='service',
            name='medium_tendency_price',
            field=models.FloatField(default=0),
        ),
    ]
