# Generated by Django 5.1.3 on 2024-11-30 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_service_heavy_tendency_maximum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='service',
            field=models.ForeignKey(default=15, on_delete=django.db.models.deletion.CASCADE, to='users.service'),
            preserve_default=False,
        ),
    ]
